#  test_id: 用户ID
#  module: 模块
#  name: 标题名称
#  priority: 优先级
#  URL: "/company-browse.html"
#  preposition: 前置
#  expected_result: 预期结果
#  actual_result: 实际结果
#  data 操作的数据结构
---
#登录
login:
  url: "https://platform.giiatop.com/cip/#/login"
  login_account: "gd-sxxh-002"
  password: "gd-sxxh-002"
  login_pass_url: "https://platform.giiatop.com/cip/#/PracticeCMS/Home"
  code: "test"
  new_url: "https://platform.giiatop.com/cip/#/"

#数字概览
overview_digital:
    test_id: "test_overview_digital_001"
    module: "首页-数字概览"
    name: "验证 总已参训人数/总计划人数相关字段、总达标人数/总参训人数  是否计算正确"
    priority: "高"
    URL: "PracticeCMS/Home"
    preposition: "成功登录"
    expected_result: "相关数据计算正确"
    actual_result: True
    data:
#参训达标走势图
charts:
    test_id: "test_overview_digital_002"
    module: "首页-数字概览"
    name: "验证 参训/达标走势图  是否正确返回"
    priority: "高"
    URL: "PracticeCMS/Home"
    preposition: "成功登录"
    expected_result: "正确返回走势图数据"
    actual_result: True
    data:
